test_arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  theta_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta_1
    pid: {p: 18000.0, i: 220, d: 320.0}
  theta_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: theta_2
    pid: {p: 18000.0, i: 360, d: 700}
  d_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: d_3
    pid: {p: 5000.0, i: 1000, d: 10000.0}
