// Generated by gencpp from file scara_kinematics/JointSpaceVelocitiesResponse.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIESRESPONSE_H
#define SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_kinematics
{
template <class ContainerAllocator>
struct JointSpaceVelocitiesResponse_
{
  typedef JointSpaceVelocitiesResponse_<ContainerAllocator> Type;

  JointSpaceVelocitiesResponse_()
    {
    }
  JointSpaceVelocitiesResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JointSpaceVelocitiesResponse_

typedef ::scara_kinematics::JointSpaceVelocitiesResponse_<std::allocator<void> > JointSpaceVelocitiesResponse;

typedef boost::shared_ptr< ::scara_kinematics::JointSpaceVelocitiesResponse > JointSpaceVelocitiesResponsePtr;
typedef boost::shared_ptr< ::scara_kinematics::JointSpaceVelocitiesResponse const> JointSpaceVelocitiesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace scara_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_kinematics/JointSpaceVelocitiesResponse";
  }

  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointSpaceVelocitiesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::scara_kinematics::JointSpaceVelocitiesResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIESRESPONSE_H
