// Generated by gencpp from file scara_kinematics/JointSpaceVelocities.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIES_H
#define SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIES_H

#include <ros/service_traits.h>


#include <scara_kinematics/JointSpaceVelocitiesRequest.h>
#include <scara_kinematics/JointSpaceVelocitiesResponse.h>


namespace scara_kinematics
{

struct JointSpaceVelocities
{

typedef JointSpaceVelocitiesRequest Request;
typedef JointSpaceVelocitiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointSpaceVelocities
} // namespace scara_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_kinematics::JointSpaceVelocities > {
  static const char* value()
  {
    return "25f781ef521cc3be875209dc009a9749";
  }

  static const char* value(const ::scara_kinematics::JointSpaceVelocities&) { return value(); }
};

template<>
struct DataType< ::scara_kinematics::JointSpaceVelocities > {
  static const char* value()
  {
    return "scara_kinematics/JointSpaceVelocities";
  }

  static const char* value(const ::scara_kinematics::JointSpaceVelocities&) { return value(); }
};


// service_traits::MD5Sum< ::scara_kinematics::JointSpaceVelocitiesRequest> should match
// service_traits::MD5Sum< ::scara_kinematics::JointSpaceVelocities >
template<>
struct MD5Sum< ::scara_kinematics::JointSpaceVelocitiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::JointSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::JointSpaceVelocitiesRequest> should match
// service_traits::DataType< ::scara_kinematics::JointSpaceVelocities >
template<>
struct DataType< ::scara_kinematics::JointSpaceVelocitiesRequest>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::JointSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_kinematics::JointSpaceVelocitiesResponse> should match
// service_traits::MD5Sum< ::scara_kinematics::JointSpaceVelocities >
template<>
struct MD5Sum< ::scara_kinematics::JointSpaceVelocitiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::JointSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::JointSpaceVelocitiesResponse> should match
// service_traits::DataType< ::scara_kinematics::JointSpaceVelocities >
template<>
struct DataType< ::scara_kinematics::JointSpaceVelocitiesResponse>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::JointSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::JointSpaceVelocitiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_JOINTSPACEVELOCITIES_H
