// Generated by gencpp from file scara_kinematics/MoveToPoint.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_MOVETOPOINT_H
#define SCARA_KINEMATICS_MESSAGE_MOVETOPOINT_H

#include <ros/service_traits.h>


#include <scara_kinematics/MoveToPointRequest.h>
#include <scara_kinematics/MoveToPointResponse.h>


namespace scara_kinematics
{

struct MoveToPoint
{

typedef MoveToPointRequest Request;
typedef MoveToPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToPoint
} // namespace scara_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_kinematics::MoveToPoint > {
  static const char* value()
  {
    return "876693826d47854f5c124f2fdb25826a";
  }

  static const char* value(const ::scara_kinematics::MoveToPoint&) { return value(); }
};

template<>
struct DataType< ::scara_kinematics::MoveToPoint > {
  static const char* value()
  {
    return "scara_kinematics/MoveToPoint";
  }

  static const char* value(const ::scara_kinematics::MoveToPoint&) { return value(); }
};


// service_traits::MD5Sum< ::scara_kinematics::MoveToPointRequest> should match
// service_traits::MD5Sum< ::scara_kinematics::MoveToPoint >
template<>
struct MD5Sum< ::scara_kinematics::MoveToPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::MoveToPoint >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::MoveToPointRequest> should match
// service_traits::DataType< ::scara_kinematics::MoveToPoint >
template<>
struct DataType< ::scara_kinematics::MoveToPointRequest>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::MoveToPoint >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_kinematics::MoveToPointResponse> should match
// service_traits::MD5Sum< ::scara_kinematics::MoveToPoint >
template<>
struct MD5Sum< ::scara_kinematics::MoveToPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::MoveToPoint >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::MoveToPointResponse> should match
// service_traits::DataType< ::scara_kinematics::MoveToPoint >
template<>
struct DataType< ::scara_kinematics::MoveToPointResponse>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::MoveToPoint >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_MOVETOPOINT_H
