// Generated by gencpp from file scara_kinematics/MoveToPointRequest.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_MOVETOPOINTREQUEST_H
#define SCARA_KINEMATICS_MESSAGE_MOVETOPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace scara_kinematics
{
template <class ContainerAllocator>
struct MoveToPointRequest_
{
  typedef MoveToPointRequest_<ContainerAllocator> Type;

  MoveToPointRequest_()
    : end_pose()  {
    }
  MoveToPointRequest_(const ContainerAllocator& _alloc)
    : end_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _end_pose_type;
  _end_pose_type end_pose;





  typedef boost::shared_ptr< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToPointRequest_

typedef ::scara_kinematics::MoveToPointRequest_<std::allocator<void> > MoveToPointRequest;

typedef boost::shared_ptr< ::scara_kinematics::MoveToPointRequest > MoveToPointRequestPtr;
typedef boost::shared_ptr< ::scara_kinematics::MoveToPointRequest const> MoveToPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator2> & rhs)
{
  return lhs.end_pose == rhs.end_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08fee3ac26cd0926e5d192afd941fb4e";
  }

  static const char* value(const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08fee3ac26cd0926ULL;
  static const uint64_t static_value2 = 0xe5d192afd941fb4eULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_kinematics/MoveToPointRequest";
  }

  static const char* value(const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose end_pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.end_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_kinematics::MoveToPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_kinematics::MoveToPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "end_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.end_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_MOVETOPOINTREQUEST_H
