// Generated by gencpp from file scara_kinematics/MoveRobot_3Response.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3RESPONSE_H
#define SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_kinematics
{
template <class ContainerAllocator>
struct MoveRobot_3Response_
{
  typedef MoveRobot_3Response_<ContainerAllocator> Type;

  MoveRobot_3Response_()
    : effort(0.0)  {
    }
  MoveRobot_3Response_(const ContainerAllocator& _alloc)
    : effort(0.0)  {
  (void)_alloc;
    }



   typedef float _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobot_3Response_

typedef ::scara_kinematics::MoveRobot_3Response_<std::allocator<void> > MoveRobot_3Response;

typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Response > MoveRobot_3ResponsePtr;
typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Response const> MoveRobot_3ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator2> & rhs)
{
  return lhs.effort == rhs.effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2913ef668deee8c9d4fa6534272a86c";
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2913ef668deee8cULL;
  static const uint64_t static_value2 = 0x9d4fa6534272a86cULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_kinematics/MoveRobot_3Response";
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 effort\n"
"\n"
;
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobot_3Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_kinematics::MoveRobot_3Response_<ContainerAllocator>& v)
  {
    s << indent << "effort: ";
    Printer<float>::stream(s, indent + "  ", v.effort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3RESPONSE_H
