// Generated by gencpp from file scara_kinematics/MoveToJoints.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_MOVETOJOINTS_H
#define SCARA_KINEMATICS_MESSAGE_MOVETOJOINTS_H

#include <ros/service_traits.h>


#include <scara_kinematics/MoveToJointsRequest.h>
#include <scara_kinematics/MoveToJointsResponse.h>


namespace scara_kinematics
{

struct MoveToJoints
{

typedef MoveToJointsRequest Request;
typedef MoveToJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveToJoints
} // namespace scara_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_kinematics::MoveToJoints > {
  static const char* value()
  {
    return "4938f680caba403e8ef27465568d7ea8";
  }

  static const char* value(const ::scara_kinematics::MoveToJoints&) { return value(); }
};

template<>
struct DataType< ::scara_kinematics::MoveToJoints > {
  static const char* value()
  {
    return "scara_kinematics/MoveToJoints";
  }

  static const char* value(const ::scara_kinematics::MoveToJoints&) { return value(); }
};


// service_traits::MD5Sum< ::scara_kinematics::MoveToJointsRequest> should match
// service_traits::MD5Sum< ::scara_kinematics::MoveToJoints >
template<>
struct MD5Sum< ::scara_kinematics::MoveToJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::MoveToJoints >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::MoveToJointsRequest> should match
// service_traits::DataType< ::scara_kinematics::MoveToJoints >
template<>
struct DataType< ::scara_kinematics::MoveToJointsRequest>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::MoveToJoints >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_kinematics::MoveToJointsResponse> should match
// service_traits::MD5Sum< ::scara_kinematics::MoveToJoints >
template<>
struct MD5Sum< ::scara_kinematics::MoveToJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::MoveToJoints >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::MoveToJointsResponse> should match
// service_traits::DataType< ::scara_kinematics::MoveToJoints >
template<>
struct DataType< ::scara_kinematics::MoveToJointsResponse>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::MoveToJoints >::value();
  }
  static const char* value(const ::scara_kinematics::MoveToJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_MOVETOJOINTS_H
