// Generated by gencpp from file scara_kinematics/MoveRobot_3Request.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3REQUEST_H
#define SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_kinematics
{
template <class ContainerAllocator>
struct MoveRobot_3Request_
{
  typedef MoveRobot_3Request_<ContainerAllocator> Type;

  MoveRobot_3Request_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , t(0.0)  {
    }
  MoveRobot_3Request_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , t(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobot_3Request_

typedef ::scara_kinematics::MoveRobot_3Request_<std::allocator<void> > MoveRobot_3Request;

typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Request > MoveRobot_3RequestPtr;
typedef boost::shared_ptr< ::scara_kinematics::MoveRobot_3Request const> MoveRobot_3RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.t == rhs.t;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator1> & lhs, const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8521e32f4ee825b52388d4b7befe536c";
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8521e32f4ee825b5ULL;
  static const uint64_t static_value2 = 0x2388d4b7befe536cULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_kinematics/MoveRobot_3Request";
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 t\n"
;
  }

  static const char* value(const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobot_3Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_kinematics::MoveRobot_3Request_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "t: ";
    Printer<float>::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_MOVEROBOT_3REQUEST_H
