// Generated by gencpp from file scara_kinematics/TaskSpaceVelocities.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIES_H
#define SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIES_H

#include <ros/service_traits.h>


#include <scara_kinematics/TaskSpaceVelocitiesRequest.h>
#include <scara_kinematics/TaskSpaceVelocitiesResponse.h>


namespace scara_kinematics
{

struct TaskSpaceVelocities
{

typedef TaskSpaceVelocitiesRequest Request;
typedef TaskSpaceVelocitiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskSpaceVelocities
} // namespace scara_kinematics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scara_kinematics::TaskSpaceVelocities > {
  static const char* value()
  {
    return "9a192cb5d2f6b202f97255024ecba4e7";
  }

  static const char* value(const ::scara_kinematics::TaskSpaceVelocities&) { return value(); }
};

template<>
struct DataType< ::scara_kinematics::TaskSpaceVelocities > {
  static const char* value()
  {
    return "scara_kinematics/TaskSpaceVelocities";
  }

  static const char* value(const ::scara_kinematics::TaskSpaceVelocities&) { return value(); }
};


// service_traits::MD5Sum< ::scara_kinematics::TaskSpaceVelocitiesRequest> should match
// service_traits::MD5Sum< ::scara_kinematics::TaskSpaceVelocities >
template<>
struct MD5Sum< ::scara_kinematics::TaskSpaceVelocitiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::TaskSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::TaskSpaceVelocitiesRequest> should match
// service_traits::DataType< ::scara_kinematics::TaskSpaceVelocities >
template<>
struct DataType< ::scara_kinematics::TaskSpaceVelocitiesRequest>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::TaskSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scara_kinematics::TaskSpaceVelocitiesResponse> should match
// service_traits::MD5Sum< ::scara_kinematics::TaskSpaceVelocities >
template<>
struct MD5Sum< ::scara_kinematics::TaskSpaceVelocitiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scara_kinematics::TaskSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scara_kinematics::TaskSpaceVelocitiesResponse> should match
// service_traits::DataType< ::scara_kinematics::TaskSpaceVelocities >
template<>
struct DataType< ::scara_kinematics::TaskSpaceVelocitiesResponse>
{
  static const char* value()
  {
    return DataType< ::scara_kinematics::TaskSpaceVelocities >::value();
  }
  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIES_H
