// Generated by gencpp from file scara_kinematics/TaskSpaceVelocitiesResponse.msg
// DO NOT EDIT!


#ifndef SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIESRESPONSE_H
#define SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scara_kinematics
{
template <class ContainerAllocator>
struct TaskSpaceVelocitiesResponse_
{
  typedef TaskSpaceVelocitiesResponse_<ContainerAllocator> Type;

  TaskSpaceVelocitiesResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , wx(0.0)
    , wy(0.0)
    , wz(0.0)  {
    }
  TaskSpaceVelocitiesResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , wx(0.0)
    , wy(0.0)
    , wz(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _wx_type;
  _wx_type wx;

   typedef double _wy_type;
  _wy_type wy;

   typedef double _wz_type;
  _wz_type wz;





  typedef boost::shared_ptr< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskSpaceVelocitiesResponse_

typedef ::scara_kinematics::TaskSpaceVelocitiesResponse_<std::allocator<void> > TaskSpaceVelocitiesResponse;

typedef boost::shared_ptr< ::scara_kinematics::TaskSpaceVelocitiesResponse > TaskSpaceVelocitiesResponsePtr;
typedef boost::shared_ptr< ::scara_kinematics::TaskSpaceVelocitiesResponse const> TaskSpaceVelocitiesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator1> & lhs, const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.wx == rhs.wx &&
    lhs.wy == rhs.wy &&
    lhs.wz == rhs.wz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator1> & lhs, const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scara_kinematics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b0a1f9128335871daf9429e0c162294";
  }

  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b0a1f9128335871ULL;
  static const uint64_t static_value2 = 0xdaf9429e0c162294ULL;
};

template<class ContainerAllocator>
struct DataType< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scara_kinematics/TaskSpaceVelocitiesResponse";
  }

  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Outputs\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 wx\n"
"float64 wy\n"
"float64 wz\n"
;
  }

  static const char* value(const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.wx);
      stream.next(m.wy);
      stream.next(m.wz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskSpaceVelocitiesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scara_kinematics::TaskSpaceVelocitiesResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "wx: ";
    Printer<double>::stream(s, indent + "  ", v.wx);
    s << indent << "wy: ";
    Printer<double>::stream(s, indent + "  ", v.wy);
    s << indent << "wz: ";
    Printer<double>::stream(s, indent + "  ", v.wz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCARA_KINEMATICS_MESSAGE_TASKSPACEVELOCITIESRESPONSE_H
